autocmd FileType javascript noremap <buffer> <C-S-L> :call JsBeautify()<cr>         " Ctrl + Shit + l
autocmd FileType json noremap <buffer> <C-S-L> :call JsonBeautify()<cr>             " Ctrl + Shit + l
autocmd FileType jsx noremap <buffer> <C-S-L> :call JsxBeautify()<cr>               " Ctrl + Shit + l
autocmd FileType html noremap <buffer> <C-S-L> :call HtmlBeautify()<cr>             " Ctrl + Shit + l
autocmd FileType css noremap <buffer> <C-S-L> :call CSSBeautify()<cr>               " Ctrl + Shit + l
autocmd FileType javascript vnoremap <buffer> <C-S-L> :call RangeJsBeautify()<cr>   " Ctrl + Shit + l
autocmd FileType json vnoremap <buffer> <C-S-L> :call RangeJsonBeautify()<cr>       " Ctrl + Shit + l
autocmd FileType jsx vnoremap <buffer> <C-S-L> :call RangeJsxBeautify()<cr>         " Ctrl + Shit + l
autocmd FileType html vnoremap <buffer> <C-S-L> :call RangeHtmlBeautify()<cr>       " Ctrl + Shit + l
autocmd FileType css vnoremap <buffer> <C-S-L> :call RangeCSSBeautify()<cr>         " Ctrl + Shit + l